# Generated by Django 2.0.3 on 2018-06-21 05:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='区域', max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='城市', max_length=5, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('is_success', models.BooleanField(default=False)),
                ('info', models.TextField(blank=True, null=True)),
                ('create_time', models.DateField(auto_now_add=True, verbose_name='创建日期')),
                ('modify_time', models.DateField(default=django.utils.timezone.now, verbose_name='最后修改日期')),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.Address')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='部门', max_length=8, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=8, verbose_name='姓名')),
                ('gender', models.CharField(choices=[('女', '女'), ('男', '男')], max_length=1, verbose_name='性别')),
                ('phone', models.CharField(help_text='手机号码', max_length=11, unique=True, verbose_name='手机号码')),
                ('tel', models.CharField(blank=True, help_text='电话', max_length=11, null=True, unique=True, verbose_name='电话')),
                ('remark', models.CharField(blank=True, help_text='备注', max_length=20)),
                ('create_time', models.DateField(auto_now_add=True, verbose_name='创建日期')),
                ('modify_time', models.DateField(default=django.utils.timezone.now, verbose_name='最后修改日期')),
                ('company', models.ForeignKey(help_text='公司', on_delete=django.db.models.deletion.CASCADE, to='data.Company')),
                ('department', models.ForeignKey(help_text='部门', on_delete=django.db.models.deletion.CASCADE, to='data.Department')),
            ],
        ),
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', help_text='公司行业', max_length=10)),
                ('info', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='职位', max_length=8, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('民营', '民营企业'), ('合资', '合资企业'), ('个体', '个体企业'), ('外资', '外资企业')], default='民营', help_text='公司性质', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='省份', max_length=5, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='区域', max_length=10, unique=True)),
                ('city', models.ForeignKey(help_text='城市', on_delete=django.db.models.deletion.CASCADE, to='data.City')),
            ],
        ),
        migrations.AddField(
            model_name='employees',
            name='position',
            field=models.ForeignKey(help_text='职位', on_delete=django.db.models.deletion.CASCADE, to='data.Position'),
        ),
        migrations.AddField(
            model_name='company',
            name='industry',
            field=models.ManyToManyField(help_text='行业', to='data.Industry'),
        ),
        migrations.AddField(
            model_name='company',
            name='property',
            field=models.ForeignKey(blank=True, help_text='企业性质', null=True, on_delete=django.db.models.deletion.CASCADE, to='data.Property'),
        ),
        migrations.AddField(
            model_name='company',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Zone'),
        ),
        migrations.AddField(
            model_name='city',
            name='province',
            field=models.ForeignKey(help_text='省份', on_delete=django.db.models.deletion.CASCADE, to='data.Province'),
        ),
        migrations.AddField(
            model_name='address',
            name='zone',
            field=models.ForeignKey(help_text='区域', on_delete=django.db.models.deletion.CASCADE, to='data.Zone'),
        ),
    ]
