# Generated by Django 2.0.3 on 2018-06-17 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='province',
        ),
        migrations.RemoveField(
            model_name='zone',
            name='province',
        ),
    ]
