# Generated by Django 2.0.3 on 2018-06-21 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='zone',
        ),
    ]
