# Generated by Django 2.0.3 on 2018-06-17 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20180617_2137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='city',
        ),
        migrations.RemoveField(
            model_name='company',
            name='zone',
        ),
    ]
