# Generated by Django 2.0.3 on 2018-06-17 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_auto_20180617_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(blank=True, help_text='部门', max_length=8, null=True, unique=True),
        ),
    ]
